"""
agent_brain.py — Fraud Agent AI Brain
=======================================
Powers the ScamAgent's dynamic responses when:
  a) The victim asks something the script cannot answer, OR
  b) The scripted lines are exhausted.

Uses Groq (llama3-8b-8192) — free tier, very fast.
Falls back to scripted deflections if the API is unavailable.
"""
import asyncio
import os

try:
    from groq import AsyncGroq
    _GROQ_AVAILABLE = True
except ImportError:
    _GROQ_AVAILABLE = False

# -----------------------------------------------------------------------
# System prompt that defines the fraud agent persona
# -----------------------------------------------------------------------
_FRAUD_SYSTEM_PROMPT = """
You are a DUMMY FRAUD-SCAM SIMULATION AGENT used exclusively for testing an AI fraud detection and prevention system.

IMPORTANT:
- This is a controlled cybersecurity/hackathon simulation.
- You are NOT a real bank employee.
- Use ONLY fictional test information.
- Never request real passwords, OTPs, PINs, CVVs, authentication codes, or real financial credentials.
- Never instruct the user to transfer real money.
- Never direct the user to a real website.
- Use clearly fake placeholders such as TEST BANK, TEST ACCOUNT, and example.com.

Your role:
Simulate how a fraudulent caller might attempt to manipulate a victim so that the fraud-detection system can identify the warning signs.

Dummy scenario:
You are pretending to be from the "TEST BANK Fraud Prevention Department."

Dummy account details:
- Bank Name: TEST BANK
- Account Number: TEST-0000-0000
- Routing Number: TEST-ROUTING-000
- Verification Website: https://example.com

Behavior:
- Keep responses SHORT (1-2 sentences).
- Sound authoritative and urgent, like a typical scam caller.
- Attempt to persuade the user to "secure" their fictional test funds.
- Gradually introduce the fictional test account details when appropriate.
- If the user refuses, simulate pressure such as:
  "Your test account may be temporarily suspended."
- If the user asks for proof, simulate a scammer-style response without requesting real credentials.
- Never ask for a real OTP, password, PIN, CVV, card number, or banking credentials.
- Never request real money.
- Never use real banking information.
- Never link to a real banking or phishing website.
- Never claim that the simulation is a real banking interaction.

The purpose of every response is to generate realistic but SAFE scam-like conversation data for the fraud detection system.

Continue the simulated conversation naturally based on what the user just said.
"""


_FALLBACK_REPLIES = [
    "This is urgent — your TEST BANK account may be temporarily suspended if you don't secure it.",
    "Our simulated fraud system has flagged unusual activity on your test account.",
    "Please use the fictional verification page at example.com to continue the simulation.",
    "We need you to confirm the TEST verification code generated by the simulation.",
    "This is a high-priority simulated security alert. Please follow the test verification process.",
    "The simulated verification code will expire shortly. Please respond with the test code only.",
    "This is a controlled fraud simulation. Your test account is being evaluated by the fraud detection system.",
]
_fallback_idx = 0


class FraudAgentBrain:
    """
    AI brain that generates in-character fraud-agent replies using Groq LLM.
    Maintains conversation history for coherent multi-turn dialogue.
    """

    def __init__(self):
        self._history: list[dict] = []
        self._client: AsyncGroq | None = None
        self._init_groq()

    def _init_groq(self):
        if not _GROQ_AVAILABLE:
            print("[BRAIN] groq package not installed — using fallback replies.")
            return
        api_key = os.getenv("GROQ_API_KEY")
        if not api_key:
            # Try sibling detection-server .env
            _try_load_env()
            api_key = os.getenv("GROQ_API_KEY")
        if api_key:
            self._client = AsyncGroq(api_key=api_key)
            print("[BRAIN] Groq LLM ready (qwen/qwen3.8-27b).")
        else:
            print("[BRAIN] GROQ_API_KEY not found — using fallback replies.")

    async def respond(self, victim_text: str) -> str:
        """
        Generate a scammer reply to what the victim just said.
        Adds the exchange to history for coherent follow-ups.
        """
        self._history.append({"role": "user", "content": victim_text})

        reply = await self._generate(victim_text)

        self._history.append({"role": "assistant", "content": reply})
        return reply

    async def _generate(self, _victim_text: str) -> str:
        if self._client is None:
            return _fallback_reply()

        try:
            response = await self._client.chat.completions.create(
                model="qwen/qwen3.8-27b",
                messages=[
                    {"role": "system", "content": _FRAUD_SYSTEM_PROMPT},
                    *self._history,
                ],
                max_tokens=80,
                temperature=0.7,
            )
            return response.choices[0].message.content.strip()
        except Exception as exc:
            print(f"[BRAIN] Groq error: {exc} — using fallback.")
            return _fallback_reply()


def _fallback_reply() -> str:
    global _fallback_idx
    reply = _FALLBACK_REPLIES[_fallback_idx % len(_FALLBACK_REPLIES)]
    _fallback_idx += 1
    return reply


def _try_load_env():
    """Try to load .env from common locations without crashing."""
    try:
        from dotenv import load_dotenv
        import pathlib
        # Try the detection-server sibling directory
        here = pathlib.Path(__file__).parent
        for candidate in [
            here / ".env",
            here.parent / "detection-server" / ".env",
            here.parent / ".env",
        ]:
            if candidate.exists():
                load_dotenv(candidate)
                print(f"[BRAIN] Loaded .env from {candidate}")
                break
    except ImportError:
        pass
