// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Ub4oGT1khdNDne-XS87l6rQwF2Ti5ok',
    appId: '1:1040647547997:web:e9dab436e0c66a084a71b4',
    messagingSenderId: '1040647547997',
    projectId: 'hackathena-a7103',
    authDomain: 'hackathena-a7103.firebaseapp.com',
    storageBucket: 'hackathena-a7103.firebasestorage.app',
    measurementId: 'G-W0GL27FNB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4CVzRNdCXOYsxa6p8m8AdqeJYUiG4RIg',
    appId: '1:1040647547997:android:d4fe513e24602d424a71b4',
    messagingSenderId: '1040647547997',
    projectId: 'hackathena-a7103',
    storageBucket: 'hackathena-a7103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHg_X-vaAciV3b4aOE5FrRQGn43tx_WZo',
    appId: '1:1040647547997:ios:d432bdfb64490a794a71b4',
    messagingSenderId: '1040647547997',
    projectId: 'hackathena-a7103',
    storageBucket: 'hackathena-a7103.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHg_X-vaAciV3b4aOE5FrRQGn43tx_WZo',
    appId: '1:1040647547997:ios:d432bdfb64490a794a71b4',
    messagingSenderId: '1040647547997',
    projectId: 'hackathena-a7103',
    storageBucket: 'hackathena-a7103.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Ub4oGT1khdNDne-XS87l6rQwF2Ti5ok',
    appId: '1:1040647547997:web:1346ef64e5f899804a71b4',
    messagingSenderId: '1040647547997',
    projectId: 'hackathena-a7103',
    authDomain: 'hackathena-a7103.firebaseapp.com',
    storageBucket: 'hackathena-a7103.firebasestorage.app',
    measurementId: 'G-MMYED4LXWY',
  );
}
